/* empty css                      */(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function l(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=l(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",()=>{const r=document.querySelector(".demo-btn"),o=document.getElementById("fullscreenBtn"),l=document.querySelector(".iframe-wrapper"),i=document.getElementById("gameIframe"),e=document.getElementById("closeIframeBtn");if(!r||!o||!i||!e||!l)return;let t=!1;function a(n){i.src=n,i.classList.add("active"),l.classList.add("active"),e.classList.add("active"),r.style.display="none",t=!0}r.addEventListener("click",n=>{n.preventDefault(),t||a(r.dataset.gameUrl)}),o.addEventListener("click",n=>{n.preventDefault(),t||a(o.dataset.gameUrl),l.classList.toggle("fullscreen-section")}),e.addEventListener("click",()=>{i.src="",i.classList.remove("active"),l.classList.remove("active","fullscreen-section"),e.classList.remove("active"),r.style.display="block",t=!1})});document.addEventListener("DOMContentLoaded",()=>{const r=document.querySelector(".menu-button"),o=r.querySelector(".icon"),l=document.querySelector(".modal"),i=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const a=`
<svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M5 7H23" stroke="white" stroke-width="3" stroke-linecap="round" />
  <path d="M5 14H23" stroke="white" stroke-width="3" stroke-linecap="round" />
  <path d="M5 21H23" stroke="white" stroke-width="3" stroke-linecap="round" />
</svg>
    `,n=`
<svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M8 20L20.7279 7.27208" stroke="white" stroke-width="3" stroke-linecap="round" />
  <path d="M8 7L20.7279 19.7279" stroke="white" stroke-width="3" stroke-linecap="round" />
</svg>
    `;r.addEventListener("click",()=>{t=!t,o.innerHTML=t?n:a,t?s():c()}),i.forEach(u=>u.addEventListener("click",()=>{c(),o.innerHTML=a,t=!1})),window.addEventListener("scroll",d);function s(){l.style.display="block"}function c(){l.style.display="none"}function d(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function r(){const n=document.getElementById("site-header");return n?n.offsetHeight:0}function o(n){const s=document.getElementById(n);if(!s)return;const c=r(),d=s.getBoundingClientRect().top+window.pageYOffset-c;window.scrollTo({top:d,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(n=>{n.addEventListener("click",function(s){const c=this.getAttribute("href");if(!c)return;const[d,u]=c.split("#");if(!u)return;const f=window.location.pathname.split("/").pop();!(d===""||d==="./"||d===f||d==="./"+f)||!document.getElementById(u)||(s.preventDefault(),o(u),t(u))})});const i=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(n){e.forEach(c=>c.classList.remove("active"));const s=document.querySelector(`.navigation-item a[href*="#${n}"]`);s&&s.closest(".navigation-item").classList.add("active")}function a(){const n=window.pageYOffset+r()+100;i.forEach(s=>{const c=s.offsetTop,d=c+s.offsetHeight;n>=c&&n<d&&t(s.id)})}if(window.addEventListener("scroll",a),window.location.hash){const n=window.location.hash.substring(1);setTimeout(()=>{o(n),t(n)},300)}});
//# sourceMappingURL=index.js.map
