/* empty css                      */(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",()=>{const n=document.querySelector(".demo-btn"),s=document.getElementById("fullscreenBtn"),r=document.querySelector(".iframe-wrapper"),c=document.getElementById("gameIframe"),e=document.getElementById("closeIframeBtn");if(!n||!s||!c||!e||!r)return;let t=!1;function l(o){c.src=o,c.classList.add("active"),r.classList.add("active"),e.classList.add("active"),n.style.display="none",t=!0}n.addEventListener("click",o=>{o.preventDefault(),t||l(n.dataset.gameUrl)}),s.addEventListener("click",o=>{o.preventDefault(),t||l(s.dataset.gameUrl),r.classList.toggle("fullscreen-section")}),e.addEventListener("click",()=>{c.src="",c.classList.remove("active"),r.classList.remove("active","fullscreen-section"),e.classList.remove("active"),n.style.display="block",t=!1})});document.addEventListener("DOMContentLoaded",()=>{const n=document.querySelector(".menu-button"),s=n.querySelector(".icon"),r=document.querySelector(".modal"),c=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const l=`
<svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M5 7H23" stroke="white" stroke-width="3" stroke-linecap="round" />
  <path d="M5 14H23" stroke="white" stroke-width="3" stroke-linecap="round" />
  <path d="M5 21H23" stroke="white" stroke-width="3" stroke-linecap="round" />
</svg>
    `,o=`
<svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M8 20L20.7279 7.27208" stroke="white" stroke-width="3" stroke-linecap="round" />
  <path d="M8 7L20.7279 19.7279" stroke="white" stroke-width="3" stroke-linecap="round" />
</svg>
    `;n.addEventListener("click",()=>{t=!t,s.innerHTML=t?o:l,t?i():d()}),c.forEach(u=>u.addEventListener("click",()=>{d(),s.innerHTML=l,t=!1})),window.addEventListener("scroll",a);function i(){r.style.display="block"}function d(){r.style.display="none"}function a(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function n(){const o=document.getElementById("site-header");return o?o.offsetHeight:0}function s(o){const i=document.getElementById(o);if(!i)return;const d=n(),a=i.getBoundingClientRect().top+window.pageYOffset-d;window.scrollTo({top:a,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(o=>{o.addEventListener("click",function(i){const d=this.getAttribute("href");if(!d)return;const[a,u]=d.split("#");if(!u)return;const f=window.location.pathname.split("/").pop();!(a===""||a==="./"||a===f||a==="./"+f)||!document.getElementById(u)||(i.preventDefault(),s(u),t(u))})});const c=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(o){e.forEach(d=>d.classList.remove("active"));const i=document.querySelector(`.navigation-item a[href*="#${o}"]`);i&&i.closest(".navigation-item").classList.add("active")}function l(){const o=window.pageYOffset+n()+100;c.forEach(i=>{const d=i.offsetTop,a=d+i.offsetHeight;o>=d&&o<a&&t(i.id)})}if(window.addEventListener("scroll",l),window.location.hash){const o=window.location.hash.substring(1);setTimeout(()=>{s(o),t(o)},300)}});document.addEventListener("DOMContentLoaded",function(){const n=document.getElementById("cookie-popup"),s=document.getElementById("accept-cookies"),r=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(n.style.display="block"),s.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),n.style.display="none"}),r.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),n.style.display="none"})});const m=document.getElementById("ageModal"),p=document.getElementById("enterBtn"),g=document.getElementById("exitBtn");m&&p&&g&&(localStorage.getItem("ageConfirmed")?m.classList.add("hidden"):document.body.style.overflow="hidden",p.addEventListener("click",()=>{var n;localStorage.setItem("ageConfirmed","true"),m.classList.add("hidden"),document.body.style.overflow="",(n=document.getElementById("demo"))==null||n.scrollIntoView({behavior:"smooth",block:"start"})}),g.addEventListener("click",()=>{m.classList.add("hidden"),document.body.style.overflow=""}));
//# sourceMappingURL=index.js.map
